#!/usr/bin/env python3

import doctest, importlib, pkgutil

for module in pkgutil.walk_packages(["result"], prefix="result."):
    doctest.testmod(importlib.import_module(module.name), raise_on_error=True)
