#!/usr/bin/env python3

import doctest, importlib, mypy.api, pkgutil, sys

finder = doctest.DocTestFinder()

for module_info in pkgutil.walk_packages(["result"], prefix="result."):
    module = importlib.import_module(module_info.name)
    failure_count, _test_count = doctest.testmod(module)

    if failure_count > 0:
        exit(1)

    for test in finder.find(module, module=module):
        src = f"from {module_info.name} import *\n" + "".join(
            [e.source for e in test.examples]
        )
        stdout, stderr, result = mypy.api.run(["--allow-redefinition", "-c", src])
        if result != 0:
            print(
                f"Type check failed for {test.name} in {test.filename}", file=sys.stderr
            )
            print(stdout, file=sys.stdout)
            print(stderr, file=sys.stderr)
            exit(result)
